[package]
name = "wk-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
egui = "0.36.2"
kira = "0.12.4"
pollster = "1.0.1"
rapier3d = { version = "*", features = ["parallel"] }
wgpu = "30.0.1"
winit = "0.30.13"
freecs = { version = "5", features = ["dynamic"] }
env_logger = "0.11.11"
ron = "0.12.2"
serde = { version = "1.0.229", features = ["derive"] }
rayon = "1.12.0"
bevy_asset_loader = "0.27.0"
bevy_ecs = "0.19.1"
bevy_rapier3d = "0.36.0"
glam = "0.33.7"
gltf = "1.4.1"
bevy_replicon = "0.44.0"
bevy_renet = "5.0.0"
bevy_egui = "0.42.0"
glow = "0.18.0"
shipyard = "0.11.5"
bevy_ui = "0.19.1"
termcolor = "1.4.1"
bevy_transform_gizmo = "0.12.1"
bitcode = "0.6.9"
gilrs = "0.11.2"
bevy_asset = "0.19.1"
bevy_utils = "0.19.1"
bevy_math = "0.19.1"
bevy_tasks = "0.19.1"
bevy_reflect = "0.19.1"
bevy_animation = "0.19.1"
bevy_transform = "0.19.1"
bevy_input = "0.19.1"
bevy_time = "0.19.1"
bevy_app = "0.19.1"
